version: 0.2

env:
  variables:
    COMPOSER_ALLOW_SUPERUSER: 1
    COMPOSER_HOME: "/root/.composer"

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "[Install Phase] Installing PHP extensions and dependencies"
      - apt-get update
      - apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip git
      - docker-php-ext-configure gd --with-freetype --with-jpeg
      - docker-php-ext-install gd
      - composer install --no-interaction
  build:
    commands:
      - echo "[Build Phase] No compile stage needed for Magento files"
  post_build:
    commands:
      - echo "[Post-Build Phase] Build complete."

artifacts:
  files:
    - '**/*'
    - '!vendor/**'
    - '!var/**'
    - '!generated/**'
    - '!node_modules/**'
    - '!auth.json'

